config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("custom_lander_creator_v2.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path(
        "custom_lander/",
        include(
            "custom_lander_creator_v2.custom_lander_creator.urls",
            namespace="custom_lander_creator",
        ),
    ),
    path(
        "google_indexer/",
        include(
            "custom_lander_creator_v2.google_indexer.urls",
            namespace="google_indexer",
        ),
    ),
    # Media files
    *static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT),
]


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

custom_lander_creator_v2/custom_lander_creator/urls.py
from django.urls import path

from .views import github_redirect_view
from .views import github_repo_view
from .views import home_view
from .views import netlify_deploy_view
from .views import netlify_redirect_view
from .views import options_view

app_name = "custom_lander_creator"
urlpatterns = [
    path("", home_view, name="home"),
    path("options/", options_view, name="options"),
    path("options/netlify_redirect/", netlify_redirect_view, name="netlify_redirect"),
    path("options/github_redirect/", github_redirect_view, name="github_redirect"),
    path("create_github_repo/", github_repo_view, name="create_github_repo"),
    path("create_netlify_site/", netlify_deploy_view, name="create_netlify_site"),
]

custom_lander_creator_v2/google_indexer/urls.py
from django.urls import path

from .views import home_view
from .views import project_create_view  # Add
from .views import project_edit_view  # Add
from .views import project_list_view  # Add
from .views import project_membership_remove_view  # Add
from .views import project_membership_view  # Add
from .views import task_create_view  # Add
from .views import task_detail_view  # Add
from .views import task_list_view  # Add
from .views import task_result_view  # Add

app_name = "google_indexer"
urlpatterns = [
    path("", home_view, name="home"),
    path("task/create/", task_create_view, name="task_create"),  # Add
    path("task/list/", task_list_view, name="task_list"),  # Add
    path("task/<str:task_id>/", task_detail_view, name="task_detail"),  # Add
    path("task/<str:task_id>/result/", task_result_view, name="task_result"),  # Add
    path("project/list/", project_list_view, name="project_list"),  # Add
    path("project/create/", project_create_view, name="project_create"),  # Add
    path("project/<int:pk>/edit/", project_edit_view, name="project_edit"),  # Add
    path(
        "project/<int:pk>/membership/",
        project_membership_view,
        name="project_membership",
    ),  # Add
    path(
        "project/<int:project_pk>/membership/<int:membership_pk>/remove/",
        project_membership_remove_view,
        name="project_membership_remove",
    ),  # Add)
]

custom_lander_creator_v2/users/urls.py
from django.urls import path

from .views import user_detail_view
from .views import user_redirect_view
from .views import user_update_view

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<int:pk>/", view=user_detail_view, name="detail"),
]

custom_lander_creator_v2/google_indexer/forms.py
# forms.py

from django import forms

from .models import Project
from .models import ProjectMembership
from .models import Task


class TaskForm(forms.Form):
    TASK_TYPE_CHOICES = [
        ("indexer", "Indexer"),
        ("checker", "Checker"),
    ]

    title = forms.CharField(max_length=255, required=False, label="Task Title")
    task_type = forms.ChoiceField(choices=TASK_TYPE_CHOICES, label="Task Type")
    urls = forms.CharField(
        widget=forms.Textarea,
        label="URLs",
        help_text="Enter one URL per line.",
    )
    project = forms.ModelChoiceField(
        queryset=None,
        label="Project",
        empty_label="Select a Project",
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["project"].queryset = Project.objects.filter(memberships__user=user)


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ["name", "description"]


class ProjectMembershipForm(forms.Form):
    email = forms.EmailField(label="User Email")
    role = forms.ChoiceField(choices=ProjectMembership.ROLE_CHOICES, label="Role")


class AddToProjectForm(forms.Form):
    project = forms.ModelChoiceField(
        queryset=None,
        label="Project",
        empty_label="Select a Project",
    )

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["project"].queryset = Project.objects.filter(memberships__user=user)


class EditTaskForm(forms.ModelForm):
    class Meta:
        # add a label to the task title field
        labels = {"title": "New Task Title"}
        model = Task
        fields = ["title"]

custom_lander_creator_v2/custom_lander_creator/views.py
import secrets
import string
from urllib.parse import quote

import requests
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils.html import format_html
from django.views.generic import View

from .models import OAuthToken


# Create your views here.
class HomeView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, "custom_lander_creator/creator_index.html")


home_view = HomeView.as_view()


class OptionsView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        base_url = f"{request.scheme}://{request.get_host()}/"
        redirect_uri = base_url + "custom_lander/options/netlify_redirect"
        encoded_redirect_uri = quote(redirect_uri, safe="")
        netlify_client_id = settings.NETLIFY_CLIENT_ID

        auth_link = f"https://app.netlify.com/authorize?client_id={netlify_client_id}&response_type=code&redirect_uri={encoded_redirect_uri}"

        github_client_id = settings.GITHUB_CLIENT_ID
        characters = string.ascii_letters + string.digits + string.punctuation
        state = "".join(secrets.choice(characters) for i in range(32))
        encoded_state = quote(state, safe="")
        github_redirect_uri = f"{base_url}custom_lander/options/github_redirect/"
        github_auth_link = f"https://github.com/login/oauth/authorize?client_id={github_client_id}&state={encoded_state}&redirect_uri={github_redirect_uri}"

        github_token_exists = OAuthToken.objects.filter(
            user=request.user,
            provider="github",
        ).exists()

        netlify_token_exists = OAuthToken.objects.filter(
            user=request.user,
            provider="netlify",
        ).exists()

        context = {
            "auth_link": auth_link,
            "github_auth_link": github_auth_link,
            "github_token_exists": github_token_exists,
            "netlify_token_exists": netlify_token_exists,
        }
        return render(request, "custom_lander_creator/options/options.html", context)

    def post(self, request, *args, **kwargs):
        if "delete_github_token" in request.POST:
            OAuthToken.objects.filter(user=request.user, provider="github").delete()
            messages.success(request, "GitHub connection has been deleted.")
        if "delete_netlify_token" in request.POST:
            OAuthToken.objects.filter(user=request.user, provider="netlify").delete()
            messages.success(request, "Netlify connection has been deleted.")
        return redirect("custom_lander_creator:options")


options_view = OptionsView.as_view()


class NetlifyRedirectView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        code = request.GET.get("code")
        base_url = f"{request.scheme}://{request.get_host()}/"
        # call the netlify API to get the access token

        client_id = settings.NETLIFY_CLIENT_ID
        client_secret = settings.NETLIFY_SECRET

        redirect_uri = f"{base_url}custom_lander/options/netlify_redirect"

        # Create the payload
        payload = {
            "grant_type": "authorization_code",
            "code": code,
            "client_id": client_id,
            "client_secret": client_secret,
            "redirect_uri": redirect_uri,
        }

        response = requests.post(
            "https://api.netlify.com/oauth/token",
            data=payload,
            timeout=10,
        )

        response_json = response.json()

        http_ok = 200

        if response.status_code != http_ok:
            messages.error(
                request,
                format_html(
                    "There was an error getting the access token from Netlify."
                    "Please go back and try again.",
                ),
            )
            return render(
                request,
                "custom_lander_creator/options/netlify_redirect.html",
            )

        access_token = response_json.get("access_token")
        refresh_token = response_json.get("refresh_token")
        scope = response_json.get("scope")
        token_type = response_json.get("token_type")

        OAuthToken.objects.update_or_create(
            user=request.user,
            provider="netlify",
            defaults={
                "access_token": access_token,
                "token_type": token_type,
                "scope": scope,
                "refresh_token": refresh_token,
            },
        )

        messages.success(request, "Successfully connected to Netlify.")
        return render(request, "custom_lander_creator/options/netlify_redirect.html")


netlify_redirect_view = NetlifyRedirectView.as_view()


class GithubRedirectView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        base_url = f"{request.scheme}://{request.get_host()}/"
        code = request.GET.get("code")
        if not code:
            messages.error(
                request,
                "Authorization code not provided. Please go back and try again.",
            )
            return render(request, "custom_lander_creator/options/github_redirect.html")
        # call the netlify API to get the access token
        client_id = settings.GITHUB_CLIENT_ID
        client_secret = settings.GITHUB_CLIENT_SECRET
        redirect_uri = base_url + "custom_lander/options/github_redirect/"

        # Create the payload
        payload = {
            "code": code,
            "client_id": client_id,
            "client_secret": client_secret,
            "redirect_uri": redirect_uri,
        }
        headers = {"Accept": "application/json"}

        response = requests.post(
            "https://github.com/login/oauth/access_token",
            data=payload,
            headers=headers,
            timeout=10,
        )

        http_ok = 200
        if response.status_code != http_ok:
            messages.error(
                request,
                "Failed to get access token. Please go back and try again.",
            )
            return render(request, "custom_lander_creator/options/github_redirect.html")

        response_data = response.json()
        if "access_token" not in response_data:
            response_json = response.json()
            response_json["redirect_uri"] = redirect_uri
            messages.error(
                request,
                "Access token not found. Please go back and try again.",
            )
            return render(request, "custom_lander_creator/options/github_redirect.html")

        access_token = response_data["access_token"]
        token_type = response_data.get("token_type", "")
        scope = response_data.get("scope", "")

        OAuthToken.objects.update_or_create(
            user=request.user,
            provider="github",
            defaults={
                "access_token": access_token,
                "token_type": token_type,
                "scope": scope,
            },
        )

        messages.success(request, "Successfully connected to GitHub.")
        return render(request, "custom_lander_creator/options/github_redirect.html")


github_redirect_view = GithubRedirectView.as_view()


class GithubRepoView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        return render(request, "custom_lander_creator/create_github_repo.html")

    def post(self, request, *args, **kwargs):
        token_record = OAuthToken.objects.filter(user=request.user, provider="github")
        access_token = token_record[0].access_token
        headers = {
            "Accept": "application/vnd.github+json",
            "Authorization": f"Bearer {access_token}",
            "X-GitHub-Api-Version": "2022-11-28",
        }

        # grab repo name, description, homepage, private, and is_template from the form
        repo_name = request.POST.get("repo_name")
        repo_description = request.POST.get("repo_description")
        repo_homepage = request.POST.get("repo_homepage")
        repo_private = request.POST.get("repo_private")
        repo_is_template = request.POST.get("repo_is_template")

        data = {
            "name": repo_name,
            "description": repo_description,
            "homepage": repo_homepage,
            "private": repo_private == "on",
            "is_template": repo_is_template == "on",
        }

        response = requests.post(
            "https://api.github.com/user/repos",
            headers=headers,
            json=data,
            timeout=10,
        )

        # Check the response
        http_ok = 201
        http_no_perm = 403
        if response.status_code == http_ok:
            # set up success message for django jinja template
            messages.success(
                request,
                f"Successfully created GitHub repository {repo_name}.",
            )
            return render(request, "custom_lander_creator/create_github_repo.html")
        if response.status_code == http_no_perm:
            # set up error message for django jinja template
            messages.error(
                request,
                format_html(
                    f"Failed to create GitHub repository {repo_name}."
                    "You need to install the app"
                    "<a href='https://github.com/apps/custom-lander-creator'"
                    "target='_blank'>"
                    "Install Custom Lander Creator</a> on your GitHub account.",
                ),
            )
            return render(request, "custom_lander_creator/create_github_repo.html")

        # set up error message for django jinja template
        messages.error(
            request,
            f"Failed to create GitHub repository {repo_name}.",
        )

custom_lander_creator_v2/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView

from custom_lander_creator_v2.users.models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "id"
    slug_url_kwarg = "id"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["name"]
    success_message = _("Information successfully updated")

    def get_success_url(self):
        # for mypy to know that the user is authenticated
        assert self.request.user.is_authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"pk": self.request.user.pk})


user_redirect_view = UserRedirectView.as_view()

custom_lander_creator_v2/templates/custom_lander_creator/create_github_repo.html
{% extends "custom_lander_creator/custom_lander_creator_base.html" %}

{% block title %}
  Custom Lander Creator Dash
{% endblock title %}
{% block inner_content %}
  <form method="post"
        action="{% url 'custom_lander_creator:create_github_repo' %}"
        class="needs-validation"
        novalidate>
    {% csrf_token %}
    <div class="form-group">
      <label for="repo_name">Repository Name:</label>
      <input type="text"
             id="repo_name"
             name="repo_name"
             class="form-control"
             required />
    </div>
    <div class="form-group">
      <label for="repo_description">Description:</label>
      <input type="text"
             id="repo_description"
             name="repo_description"
             class="form-control"
             required />
    </div>
    <div class="form-group">
      <label for="repo_homepage">Homepage:</label>
      <input type="url"
             id="repo_homepage"
             name="repo_homepage"
             class="form-control" />
    </div>
    <div class="form-check">
      <input type="checkbox"
             id="repo_private"
             name="repo_private"
             class="form-check-input" />
      <label for="repo_private" class="form-check-label">Private</label>
    </div>
    <div class="form-check">
      <input type="checkbox"
             id="repo_is_template"
             name="repo_is_template"
             class="form-check-input" />
      <label for="repo_is_template" class="form-check-label">Is Template</label>
    </div>
    <button type="submit" class="btn btn-primary">Create Repository</button>
  </form>
{% endblock inner_content %}

custom_lander_creator_v2/templates/custom_lander_creator/create_netlify_site.html
{% extends "custom_lander_creator/custom_lander_creator_base.html" %}

{% block title %}
  Custom Lander Creator Dash
{% endblock title %}
{% block inner_content %}
  <form method="post"
        action="{% url 'custom_lander_creator:create_netlify_site' %}"
        class="needs-validation"
        novalidate>
    {% csrf_token %}
    <div class="form-group">
      <label for="repo_name">Repository Name:</label>
      <input type="text"
             id="repo_name"
             name="repo_name"
             class="form-control"
             required />
    </div>
    <div class="form-group">
      <label for="gh_username">User Name:</label>
      <input type="text"
             id="gh_username"
             name="gh_username"
             class="form-control"
             required />
    </div>
    <div class="form-group">
      <label for="site_name">Site Name:</label>
      <input type="text"
             id="site_name"
             name="site_name"
             class="form-control"
             required />
    </div>
    <div class="form-group">
      <label for="branch">branch:</label>
      <input type="text" id="branch" name="branch" class="form-control" />
    </div>
    <div class="form-check">
      <input type="checkbox"
             id="repo_private"
             name="repo_private"
             class="form-check-input" />
      <label for="repo_private" class="form-check-label">Private</label>
    </div>
    <button type="submit" class="btn btn-primary">Create Repository</button>
  </form>
{% endblock inner_content %}

custom_lander_creator_v2/templates/custom_lander_creator/creator_index.html
{% extends "custom_lander_creator/custom_lander_creator_base.html" %}

{% block title %}
  Custom Lander Creator Dash
{% endblock title %}
{% block inner_content %}
  <div class="container">
    <div class="row">
      <div class="col-sm-12">This is additional content for the specific panel you are on</div>
    </div>
  </div>
{% endblock inner_content %}

custom_lander_creator_v2/templates/custom_lander_creator/custom_lander_creator_base.html
{% extends "base.html" %}

{% load static %}

{% block title %}
  Custom Lander Creator
{% endblock title %}
{% block content %}
  <div class="container-fluid">
    <div class="row">
      <nav id="sidebarMenu"
           class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
        <div class="position-sticky pt-3">
          <ul class="nav nav-pills flex-column">
            <li class="nav-item">
              {% url 'custom_lander_creator:home' as home_url %}
              <a class="nav-link {% if request.path == home_url %}active{% endif %}"
                 aria-current="page"
                 href="{{ home_url }}">
                <i class="fas fa-tachometer-alt"></i> Dashboard
              </a>
            </li>
            <li class="nav-item">
              {% url 'custom_lander_creator:create_github_repo' as github_creator %}
              <a class="nav-link {% if request.path == github_creator %}active{% endif %}"
                 href="{{ github_creator }}">
                <i class="fab fa-github"></i> Create Github Repo
              </a>
            </li>
            <li class="nav-item">
              {% url 'custom_lander_creator:create_netlify_site' as netlify_creator %}
              <a class="nav-link {% if request.path == netlify_creator %}active{% endif %}"
                 href="{{ netlify_creator }}">
                <i class="fa-solid fa-browser"></i> Create Netlify Site
              </a>
            </li>
            <li class="nav-item">
              {% url 'custom_lander_creator:options' as options_url %}
              <a class="nav-link {% if request.path == options_url %}active{% endif %}"
                 href="{{ options_url }}">
                <i class="fas fa-cogs"></i> Options
              </a>
            </li>
          </ul>
        </div>
      </nav>
      <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
        <div class="row">
          <div class="col-sm-12">
            <h2>Custom Lander Creator App</h2>
          </div>
        </div>
        {% block inner_content %}
          <!-- Page specific content goes here -->
        {% endblock inner_content %}
      </main>
    </div>
  </div>
{% endblock content %}